### ISSUE TITLE
'NotNullIfNotNullAttribute' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by Sp1rit** [mrtaikandi/MapTo#10]
The error message above is produced when I use this generator within a .NET Framework project with LangVersion=latest.
Setting SupportNullableStaticAnalysis to false in SourceGenerationOptions works for me.

C#9 is technically not fully supported for .NET Framework, but it works and we are using it for all projects. The supportNullableStaticAnalysis would need another check than just CSharp version.

**Comment by mrtaikandi** [comment]
What version of the .NET are you using?

**Comment by Sp1rit** [comment]
.NET Framework 4.7.2
