### ISSUE TITLE
add partial

### ISSUE THREAD

**Issue by ignatandrei** [mrtaikandi/MapTo#4]
For more flexibility, add a 

partial void AfterCopy( <type of the map> original)

and call in the constructor to let the people to add their implementation

**Comment by mrtaikandi** [comment]
I was planning to make the generated constructor calls the default constructor if one exists in the destination class. Do you think this will cover what you have in mind? 
For instance:

```csharp
public partial class DestinationClass
{
    public DestinationClass()
    {
        // User code.
    }

    // Other properties and methods...
}

public partial class DestinationClass
{
    public DestinationClass(....) : this()
    {
        // Generated code
    }
}
```

This way, people have the opportunity to define read-only fields/properties as well.

**Comment by ignatandrei** [comment]
Okish
But my approach will allow people to modify whenever they want e
