### ISSUE TITLE
Build fails without <MapTo_ConstructorAccessModifier> set

### ISSUE THREAD

**Issue by zbecknell** [mrtaikandi/MapTo#5]
Without setting this property my build fails with this error:

```
'' is not a valid value for MapTo_ConstructorAccessModifier property.
```

Seems like it's just missing a default value in case it's null or blank.  Workaround is to just add the property into the referencing project:

```xml
<PropertyGroup>
    <MapTo_ConstructorAccessModifier>Internal</MapTo_ConstructorAccessModifier>
</PropertyGroup>
```

**Comment by mrtaikandi** [comment]
Thanks for reporting. I addressed this issue in v0.6.3.
