### ISSUE TITLE
Use full type name in generated code.

### ISSUE THREAD

**Issue by evilz** [mrtaikandi/MapTo#6]
If you got same name for class and namespace. it not work.

for exemple

```csharp
public global::Sale.Sale Sale {
      get { return sale_; }
      set {
        sale_ = value;
      }
    }
``` 

cannot be mapped with this generated code
```csharp
public static SaleModel ToSaleModel(this Sale sale)
        {
            return sale == null ? null : new SaleModel(sale);
        }
``` 

Should be something like 

```csharp
public static SaleModel ToSaleModel(this global::Sale.Sale sale)
        {
            return sale == null ? null : new SaleModel(sale);
        }
``` 

Thank for you work 👍

**Comment by mrtaikandi** [comment]
This issue should have been fixed now. Please let me know if it is, and I will close this issue. For reference, this is its [unit test](https://github.com/mrtaikandi/MapTo/blob/e474ab86d0cbff6a2507d345ab8b3bba8eb8d85e/test/MapTo.Tests/MappedClassesTests.cs#L100).
