### ISSUE TITLE
Support mapping from methods

### ISSUE THREAD

**Issue by Serg046** [mrtaikandi/MapTo#7]
On some project I have to use quite specific API which exposes models with methods instead of properties.
For example, API model:
```csharp
class Entity
{
    int EntityId() {...}
}
```
My model:
```csharp
[MapFrom(typeof(Entity)]
partial class EntityDTO
{
    int EntityId { get; }
}
```
But, obviously, it doesn't work. What do you think about adding this? Would you accept such a PR?
If you think it is a rare case, could you consider optional support? We could add some kind of configuration like `[MapFrom(typeof(Entity), MapMethods = true)]`

**Comment by mrtaikandi** [comment]
Thanks for the suggestion but I think this is a rare case and having an extra option just for this case in the API will make it complicated for others. I think the best way to tackle this issue might be to extend the conversion API to support more complicated scenarios. 

Also, I am planning to add support for mapping profiles like Automapper. I think it is possible to have support for this scenario in that too but no promises.
